
version: "3"

services:

  application:
    build: ./app
    environment: 
      PYTHONPATH: .
    ports:
      - '5000:5000'
    links:
      - db

  db:
    image: mysql:latest
    container_name: flask_database_container
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
