
version: "3.7"

services:

  application:
    build: ./app
    container_name: api
    environment: 
      PYTHONPATH: .
    ports:
      - '5000:5000'
    links:
      - redis
  
  redis:
    build: ./redis
    container_name: redisCache
    ports:
      - '6379:6379'